# Generated by Django 3.0.1 on 2022-10-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_ab', models.CharField(default='RU', max_length=3, verbose_name='language_abbreviation')),
                ('language', models.CharField(default='RUSSIAN', max_length=100, verbose_name='full_language')),
            ],
        ),
    ]
